# Generated by Django 5.0.6 on 2024-05-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_photo_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_about',
            name='image',
            field=models.ImageField(upload_to='photos_about/'),
        ),
    ]
