# Generated by Django 5.0.6 on 2024-05-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_photo_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='foto1',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='proyectos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='foto2',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='proyectos/'),
        ),
    ]
